### PR TITLE
Consumer

### PR DESCRIPTION
**Pull request by MichaelDuPlessis**
Includes the following resolvers and reducers for creating an advert, shortlisting a bad, viewing bids and adverts and accepting a bid.

Also include the linking of viewing adverts and bids to frontend, Updated UI to only reflect what is currently in the backend, and back navigation.

### CODE REVIEW

**Comment by Alexander-Muendesi** [comment]
Let me have a look

**Review by arlo216 — APPROVED** [review]
Approval of all UI changes

**Comment by Alexander-Muendesi** [comment]
is there authentication test not a mock?

**Comment by MichaelDuPlessis** [comment]
> is there authentication test not a mock?

It doesn't appear to be, should I make it one?

**Pull request merged**
