### PR TITLE
✨ Added classes and functions required for redux

### PR DESCRIPTION
**Pull request by MichaelDuPlessis**
New library was generated for the redux design pattern as well as an example library

### CODE REVIEW

**Comment by Alexander-Muendesi** [comment]
Seems like it fails when it cant find a test which is strange. Maybe add a mock and see what happens

**Comment by Alexander-Muendesi** [comment]
okay so I think maybe we limit the Action to build the app bundle for apps/app only perhaps?

**Comment by MichaelDuPlessis** [comment]
> okay so I think maybe we limit the Action to build the app bundle for apps/app only perhaps? since its looking for stuff in libs. The script currently just builds everything it can find I think from the way I set it up
> 
> Just let me know if thats course of action you want and I will do that

I think we are going to need to limit it because it seems to be trying to find a main file in the libs folder which will never have one

**Comment by Alexander-Muendesi** [comment]
okay let me make the change. should be a quick one I think

**Review by Alexander-Muendesi — APPROVED** [review]

**Pull request merged**
