### PR TITLE
⚡️ Added final script for code coverage

### PR DESCRIPTION
**Pull request by Alexander-Muendesi**
So much effort for a badge ........

### CODE REVIEW

**Comment by MichaelDuPlessis** [comment]
When you are done with all the fixes just let me know so that I can review it

**Comment by Alexander-Muendesi** [comment]
Hold on one moment if it passes. need to add --coverage somewhere

**Comment by Alexander-Muendesi** [comment]
I am investigating something on my fork. CodeCov not cooperating here so want to see whats up. if this fails I give up

**Comment by Alexander-Muendesi** [comment]
image
It is not picking up all the lib folders even though they are all in the lcov.info file. So I think we can do without this code coverage. Flutter just doesnt seem to work with it.

**Comment by Alexander-Muendesi** [comment]
@MichaelDuPlessis  I think I am going to wait for actual unit tests to be written and see if this still does not work. maybe the mock tests were a contributor. If still nothing then we can scrap it

**Comment by MichaelDuPlessis** [comment]
> @MichaelDuPlessis I think I am going to wait for actual unit tests to be written and see if this still does not work. maybe the mock tests were a contributor. If still nothing then we can scrap it

Okay, that sounds good

**Pull request closed without merging**
